-- PostgreSQL schema-only SQL generated from u590239395_gis-2.sql
-- Includes inferred relationships (FOREIGN KEY constraints)
-- Excludes table: alameda
-- Data rows (INSERT statements) omitted

BEGIN;

-- Drop tables (dependency-safe)
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "ibaan" CASCADE;
DROP TABLE IF EXISTS "building" CASCADE;
DROP TABLE IF EXISTS "land_appraisal" CASCADE;
DROP TABLE IF EXISTS "land_assessment_summary" CASCADE;
DROP TABLE IF EXISTS "tax_other_details" CASCADE;
DROP TABLE IF EXISTS "tax_forms" CASCADE;
DROP TABLE IF EXISTS "landparcel" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Base tables
CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 15) NOT NULL,
  "username" varchar(255) NOT NULL,
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "role" integer DEFAULT 2 NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_username" UNIQUE ("username"),
  CONSTRAINT "users_email" UNIQUE ("email")
);

CREATE TABLE "landparcel" (
  "parcelID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL,
  "improvement" boolean,
  "totalValue" double precision,
  "StreetAddress" varchar(255),
  "Barangay" varchar(255),
  "Municipality" varchar(255),
  "ZipCode" integer,
  "areaSize" double precision,
  "propertyType" varchar(255),
  "actualLandUse" varchar(255),
  PRIMARY KEY ("parcelID")
);

CREATE TABLE "tax_forms" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1053) NOT NULL,
  "arpNo" varchar(50),
  "tdPrinted" boolean,
  "municipalCode" smallint,
  "accountNo" varchar(50),
  "ownerName" varchar(100),
  "ownerAddress" varchar(255),
  "administrator" varchar(100),
  "adminAddress" varchar(255),
  "north" varchar(100),
  "east" varchar(100),
  "south" varchar(100),
  "west" varchar(100),
  "propertyIndexNo" varchar(50),
  "subdivision" varchar(100),
  "phase" varchar(50),
  "lotNo" varchar(50),
  "tdPrintedNo" varchar(50),
  "houseNo" varchar(50),
  "street" varchar(100),
  "landmark" varchar(100),
  "barangay" varchar(100),
  "barangayOnPrint" boolean,
  "barangayText" varchar(100),
  "octNo" varchar(50),
  "dated" date,
  "surveyNo" varchar(50),
  "cadLotNo" varchar(50),
  "lotNo2" varchar(50),
  "blockNo" varchar(50),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

-- Dependent / related tables
CREATE TABLE "land_appraisal" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1010) NOT NULL,
  "taxid" bigint,
  "class" varchar(100),
  "subClass" varchar(100),
  "actualUse" varchar(150),
  "unitValue" numeric(12,2),
  "area" varchar(100),
  "baseMarketValue" numeric(14,2),
  "stripping" varchar(100),
  "adjustment" varchar(100),
  "marketValue" numeric(14,2),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "land_assessment_summary" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 11) NOT NULL,
  "taxId" bigint NOT NULL,
  "propertyKind" varchar(100),
  "propertyActualUse" varchar(100),
  "adjustedMarketValue" numeric(15,2),
  "level" varchar(50),
  "assessedValue" numeric(15,2),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "tax_other_details" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 55) NOT NULL,
  "taxId" bigint NOT NULL,
  "taxability" varchar(50),
  "effectivityYear" integer,
  "quarter" varchar(50),
  "updateCode" varchar(50),
  "dateRegistered" date,
  "status" varchar(50),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "ibaan" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 6804) NOT NULL,
  "ParcelId" bigint,
  "SurveyId" integer,
  "BlockNumber" varchar(50),
  "LotNumber" varchar(50),
  "Area" double precision,
  "Claimant" varchar(255),
  "TiePointId" integer,
  "TiePointNa" varchar(255),
  "SurveyPlan" varchar(100),
  "BarangayNa" varchar(255),
  "Coordinate" integer,
  "XI" double precision,
  "YI" double precision,
  "LongitudeI" double precision,
  "LatitudeI" double precision,
  "LengthI" double precision,
  "AreaI" double precision,
  "VersionI" integer,
  "tax_ID" varchar(100),
  "Tax_Amount" numeric(15,2),
  "Due_Date" date,
  "AmountPaid" numeric(15,2),
  "Date_paid" date,
  "geometry" jsonb,
  PRIMARY KEY ("id")
);

CREATE TABLE "audit_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL,
  "user_id" integer,
  "username" varchar(255) NOT NULL,
  "action" text NOT NULL CHECK ("action" IN ('CREATE','UPDATE','DELETE')),
  "entity_type" varchar(64) NOT NULL,
  "entity_id" varchar(64) NOT NULL,
  "entity_ctx" jsonb,
  "changed_fields" jsonb,
  "before_data" jsonb,
  "after_data" jsonb,
  "ip" varchar(45),
  "user_agent" varchar(255),
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "parcel_id_v" varchar(64) GENERATED ALWAYS AS (("entity_ctx"->>'ParcelId')) STORED,
  PRIMARY KEY ("id")
);

CREATE TABLE "building" (
  "building_num" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1002) NOT NULL,
  "buildingName" varchar(255),
  "buildingUseType" varchar(255),
  "buildingType" varchar(255),
  "area" varchar(255),
  PRIMARY KEY ("building_num")
);

-- Indexes (from dump)
CREATE INDEX "audit_logs_idx_entity" ON "audit_logs" ("entity_type", "entity_id", "created_at");
CREATE INDEX "audit_logs_idx_username" ON "audit_logs" ("username", "created_at");
CREATE INDEX "audit_logs_idx_created" ON "audit_logs" ("created_at");
CREATE INDEX "audit_logs_idx_parcel" ON "audit_logs" ("parcel_id_v", "created_at");

-- Helpful indexes for FK columns
CREATE INDEX "audit_logs_idx_user_id" ON "audit_logs" ("user_id");
CREATE INDEX "land_appraisal_idx_taxid" ON "land_appraisal" ("taxid");
CREATE INDEX "land_assessment_summary_idx_taxId" ON "land_assessment_summary" ("taxId");
CREATE INDEX "tax_other_details_idx_taxId" ON "tax_other_details" ("taxId");
CREATE INDEX "ibaan_idx_parcelid" ON "ibaan" ("ParcelId");

-- Relationships (inferred)
ALTER TABLE "audit_logs"
  ADD CONSTRAINT "fk_audit_logs_user"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id")
  ON DELETE SET NULL;

ALTER TABLE "land_appraisal"
  ADD CONSTRAINT "fk_land_appraisal_tax_forms"
  FOREIGN KEY ("taxid") REFERENCES "tax_forms" ("id")
  ON DELETE SET NULL;

ALTER TABLE "land_assessment_summary"
  ADD CONSTRAINT "fk_land_assessment_summary_tax_forms"
  FOREIGN KEY ("taxId") REFERENCES "tax_forms" ("id")
  ON DELETE CASCADE;

ALTER TABLE "tax_other_details"
  ADD CONSTRAINT "fk_tax_other_details_tax_forms"
  FOREIGN KEY ("taxId") REFERENCES "tax_forms" ("id")
  ON DELETE CASCADE;

ALTER TABLE "ibaan"
  ADD CONSTRAINT "fk_ibaan_landparcel"
  FOREIGN KEY ("ParcelId") REFERENCES "landparcel" ("parcelID")
  ON DELETE SET NULL;

COMMIT;
